name: Java CI

on: [push]

jobs:

  pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
          java-package: jdk

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install dpl
        run: gem install dpl

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test with Maven
        environment: pro-finances
        env:
          C_P_R_L: ${{ secrets.C_P_R_L }}
          C_S_J_S: ${{ secrets.C_S_J_S }}
          JDBC_DATABASE_PASSWORD: ${{ secrets.JDBC_DATABASE_PASSWORD }}
          JDBC_DATABASE_URL: ${{ secrets.JDBC_DATABASE_URL }}
          JDBC_DATABASE_USERNAME: ${{ secrets.JDBC_DATABASE_USERNAME }}
          S_M_H: ${{ secrets.S_M_H }}
          S_M_PA: ${{ secrets.S_M_PA }}
          S_M_PO: ${{ secrets.S_M_PO }}
          S_M_U: ${{ secrets.S_M_U }}
        run: mvn test -B
